### ISSUE TITLE
[BUG] wxmap is taking the city name truncated

### ISSUE THREAD

**Issue by stdevPavelmc** [stdevPavelmc/FAASGS#16]
See comment https://github.com/stdevPavelmc/FAASGS/issues/13#issuecomment-778592827 

wxmap is getting the city name truncated when the city or the country has a space, must workout that to pass it as al full string (quoted)

**Comment by stdevPavelmc** [comment]
Related to #13

**Comment by stdevPavelmc** [comment]
Related to #20

**Comment by stdevPavelmc** [comment]
A fix is under testing table, sadly I have not another NOAA pass until tomorrow noon.

The solution was to scape the spaces in the "city, country" string

Will push when changes are validated

**Comment by stdevPavelmc** [comment]
Fix didn't work, trying other fixes

**Comment by Murzim2** [comment]
Any progress on this one

**Comment by stdevPavelmc** [comment]
> Any progress on this one

Fixed last night by #23 ;-)

**Comment by Murzim2** [comment]
Just rebuild the system and trying it out, looks good so far.
Thanks
