### ISSUE TITLE
[BUG] RaspiOS repository rtl_fm has no -E wav option

### ISSUE THREAD

**Issue by stdevPavelmc** [stdevPavelmc/FAASGS#17]
RaspiOS repository rtl_fm soft has no -E wav option

Alternative options?
- Detect RaspiOS and install rtl_fm and others from Armbian (requires testing)
- Instruct the user to compile it (done, not elegant but works)
- Other alternative?

**Comment by stdevPavelmc** [comment]
Related to #13

**Comment by stdevPavelmc** [comment]
Related to #11

**Comment by AgriVision** [comment]
This is fixed by using AUDIO_SBS="no"

**Comment by stdevPavelmc** [comment]
Working on it now...

Fix pushed in a few minutes, good catch.
