### ISSUE TITLE
[BUG] Explain how to install predict and set the conf files.

### ISSUE THREAD

**Issue by stdevPavelmc** [stdevPavelmc/FAASGS#19]
See references:
- https://github.com/stdevPavelmc/FAASGS/issues/14#issuecomment-778827903 
- https://github.com/stdevPavelmc/FAASGS/issues/11#issuecomment-774460482

Explain better the installation of predict on the README.

**Comment by Murzim2** [comment]
As Predict didn't appear to complete the install properly this is what I did.

mkdir ~/.predict
cd ~/.predict
wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.db
wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.tle
wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.qth

Then predict runs correctly

**Comment by stdevPavelmc** [comment]
> As Predict didn't appear to complete the install properly this is what I did.

That as root, right?
