### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by Murzim2** [stdevPavelmc/FAASGS#20]
Just done the latest update and get the following error message
sed: -e expression #1, char 22: unterminated `s' command
make: *** [Makefile:37: install] Error 1

**Comment by stdevPavelmc** [comment]
Hum... I reviewed a recent report that is related to this

Can you share the contents of the first lines of your `/etc/sat_data/user.conf` file, specially the ones with the variables below, just as it's write on the file

LOC=FL11bj
LOC_NAME="Camaguey"
LOC_COUNTRY="Cuba"

**Comment by Murzim2** [comment]
Hi Pavel

I have just upgraded my Pi to use an SSD and to boot from it
So have rebuild your programme and the problem is related to having United Kingdom in LOC_COUNTRY
On a clean build your details are still in the user.conf file so is not a problem but with my country location of United Kingdom it produces the error.

**Comment by stdevPavelmc** [comment]
Yep, working on to now... related to #16
