### ISSUE TITLE
Install on Debian x86

### ISSUE THREAD

**Issue by hanslammerts** [stdevPavelmc/FAASGS#3]
Just installed this great piece of software. However, I do have some questions.
I'm running Debian 10 on a x86 SBC.

I git cloned the software, and did a make install. This went without problems.
I edited /etc/sat_data/user.conf as you described. Running sats.sh worked as well (after linking predict in /usr/bin...).
The make permanent also worked.

I now have an index.php in /var/www/html, and going there with a browser displays the webpage.
However, it looks like user.conf is never parsed.
I found another index.php in /etc/sat_data. Not sure what that one is for, but in this php file I also can't find any reference to user.conf.

Can you tell me where the files in /etc/sat_data are used ?

Tnx, PA3CRZ

**Comment by stdevPavelmc** [comment]
Hi PA3CRZ!

In deed, there are two index pages, one in the /var/www/html and another in the /etc/sat_data

The one in /var/www... is the front page you see when open the browser, and the other in /etc/sat_data is copied to each recorded directory once the RX data is parsed and processed to show it nicely and not just a directory listing...

And now I apologize, I realized now that the code to parse and show the data in the user.conf was no pushed to github, so... there is an update in the way.

Last nights I improved the listing on the recorded data (the second index) to show the 4 images (color, gray, them & 3D)

I will push the changes today at night, so stay tuned and thanks for using the software.

73

**Comment by stdevPavelmc** [comment]
Hi PA3CRZ, 

I just uploaded the latest changes, please re-read the readme (specially the Upgrading section) and test it, if you found any bug just let me know.

Thanks for using the software!

For reference, latest commit to fix this was https://github.com/stdevPavelmc/FAASGS/commit/6ed23bb3cc0a39b9bbcf2a85731aaec7bb4cf8c6

**Comment by stdevPavelmc** [comment]
Ooops!

There is a problem with the NOAA thumbnails generation, fixing, will push it in a few minutes
