### ISSUE TITLE
forecasts do not match

### ISSUE THREAD

**Issue by F1SMV** [stdevPavelmc/FAASGS#31]
![Capturehoraires](https://user-images.githubusercontent.com/64283688/109917655-f964f500-7cb5-11eb-983b-456c3c23f39c.PNG)
Hello
Attached is a copy of two screens which confirm that the transit forecasts do not work for me with the same parameters. On the left forecasts generated by the distribution https://github.com/reynico/raspberry-noaa that I have been using for 6 months with receipt without problem. On the right, the forecasts generated which seem out of place .. and obviously no reception .. what do you think?
eric

**Comment by stdevPavelmc** [comment]
Two possible issues:

## Time / date on your device, and also the timezone

Some command to check

```sh
pavel@sbc:~$ date
jue 04 mar 2021 13:40:04 CST
pavel@sbc:~$ date -u
jue 04 mar 2021 18:41:01 UTC
 ```

Check you has the correct local **and** UTC time, you can fix the timezone with `sudo dpkg-reconfigure tzdata` and set the date and time as this:

```sh
pavel@sbc:~$ date -s "March 4, 2021 18:41:01"
```
## Location missmatch

You need to set the coordinates for your QTH in the `predict` qth file `/root/.predict/predict.qth`

```sh
root@opi3:~# cat /root/.predict/predict.qth 
CO7WT
 21.xxxx
 77.xxxx
 100
root@opi3:~# 
```
**Watchout!** there is a space in front of the Lat/Lon/Alt parameters, to sign it belongs to CO7WT

That's the equivalent for:

-  CO7WT (me)
- Latitude: 21.xxxx N
- Longitude: 77.xxxx W
- Altitude: 99.908 m (Above mean sea level)

I wait for your feedback on this, cheers.

**Comment by stdevPavelmc** [comment]
Thinking now to add this steps in the readme as comments / instructions, the precise time source and the location setting.

**Comment by stdevPavelmc** [comment]
Added instructions for this case.

Please start over and follow the instructions with the new version.

**Comment by F1SMV** [comment]
GM Pavel

thank for your help : 2 things ..file predict.qth was empty in
cat/root/.predict/predict.qth
ok i send predict and make my setup..you know here latitude must be write
with -5.8734..after i run sat.sh and i cann notice that predict are good
and wrong
screen copy ..how is possible ?
hope help you.

Eric
[image: fagss.png]

**Comment by stdevPavelmc** [comment]
Hi @Eric738 

Did you still has the bad forecast problems?

**Comment by F1SMV** [comment]
yes ! after 24 h in reception no pic catch..is it possible to check the log
? with my other cfg (raspberry -noaa) and my second raspi all is ok.
thank 73 Eric

**Comment by stdevPavelmc** [comment]
Please check https://github.com/stdevPavelmc/FAASGS/issues/31#issuecomment-790846977

The N/S of the coordinate system is not intuitive, maybe you are setting the position on the wrong place

**Comment by F1SMV** [comment]
i dont think , part of the forecast of passage, and another part, no .. in my opinion that can not be a coincidence. My problem at the moment is that on the passages ok, I would have liked to have the rx of sat noaa 73 Eric
