### ISSUE TITLE
[BUG] RTL_PPM is hardcoded, but differs per RTL-SDR stick

### ISSUE THREAD

**Issue by AgriVision** [stdevPavelmc/FAASGS#33]
The rtl ppm offset, which differs for each individual stick is currently a hardcoded value in sat.sh.
I would propose to place it in user.conf and add some documentation there or in the README on how to obtain this value, e.g. rtl_test, or https://www.rtl-sdr.com/tag/ppm/, or other sources.

**Comment by stdevPavelmc** [comment]
Good catch you are right about it, and fixing is simple, WIP.

**Comment by stdevPavelmc** [comment]
Done, upgrade as usual...
