### ISSUE TITLE
Permission errors

### ISSUE THREAD

**Issue by royldean** [stdevPavelmc/FAASGS#4]
Just installed this on a Pi 3B+.   Got to the step of manually running sats.sh and I got this:
```
pi@raspberrypi:~/FAASGS $ ./sat.sh

Updating data and scheduling new sats

mkdir: cannot create directory ‘/var/www’: Permission denied

/etc/sat_data/data_temp.txt: Permission denied

Can't fetch fresh TLE data, using old one

./sat.sh: line 30: /var/www/html/sat/passes.txt: Permission denied

./sat.sh: line 48: /usr/bin/jq: No such file or directory
```

Any suggestions?

**Comment by stdevPavelmc** [comment]
My bad, I must have mentioned that little detail: **You must be root to setup and configure the software!**

Just make `sudo -i` in the terminal and follow the procedures it must work flawlessly then.

I will add a note in the readme for future users.

Thanks for using the software!

**Comment by stdevPavelmc** [comment]
Done, comment added.

Please test it and give feedback to know I can close this issue. Thanks for your time.

**Comment by royldean** [comment]
What is supposed to happen when I execute sat.sh?

All that happens is:
`Updating data and scheduling new sats`
And nothing else.  If I load the web interface, it still says "Camagüey - Cuba - FL11bj", with no scheduled passes.   But /etc/sat_data/user.conf has all of my information shown correctly.

**Comment by royldean** [comment]
I've now tried this on two seperate pi's - both are giving me the following error when I run sat.sh:
```
pi@RASPI-FOXTELEM:~/FAASGS $ sudo ./sat.sh
Updating data and scheduling new sats
Fresh data fetched, updating the good file
Filtering the sats we need and set simple names
./sat.sh: line 273: /usr/bin/jq: No such file or directory
./sat.sh: line 48: /usr/bin/jq: No such file or directory
```
